"""`swarm` — one binary, four verbs that matter: scan, dispatch, reconcile, dashboard.

The same image runs on a laptop, in GitHub Actions, in GitLab CI or in Jenkins;
the workflow YAML in `examples/target-workflows/` is only an event bus. Nothing
in this CLI assumes it is running inside GitHub Actions except the optional
`$GITHUB_STEP_SUMMARY` write.
"""

from __future__ import annotations

import argparse
import json
import os
import sys

from . import __version__
from .dashboard import render, render_metrics_json
from .devin import DevinClient, acus_today
from .dispatch import dispatch_issue
from .gh import GitHubClient
from .issues import IssueSpec, render_issue_body
from .metrics import compute, step_summary
from .models import NEEDS_HUMAN, QUEUED, REVIEW_PENDING, Ledger, Task
from .policy import Policy
from .reconcile import reconcile
from .scan import existing_fingerprints, file_issues, run_scanners
from .scheduler import plan
from .state import STATE_BRANCH, StateStore, rebuild
from .transport import LIVE, RECORD, REPLAY, Transport, read_meta
from .verify import run as verify_pr
from .verify import summary as verify_summary

CLASS_LABEL_COLOURS = {
    "class:dep-bump-patch": "0e8a16",
    "class:dep-bump-major": "d93f0b",
    "class:deprecation": "fbca04",
    "class:code-quality": "1d76db",
    "class:security": "b60205",
    "class:authz": "b60205",
    "devin:auto": "5319e7",
    "scanner": "c5def5",
    "tier:1": "c2e0c6",
    "tier:2": "fef2c0",
    "tier:3": "f9d0c4",
}
STATE_LABELS = [
    "swarm:queued", "swarm:dispatched", "swarm:running", "swarm:pr_open",
    "swarm:review_pending", "swarm:review_clean", "swarm:needs_human",
    "swarm:failed", "swarm:merged", "swarm:abandoned", "swarm:wont_fix",
]


# -- wiring -------------------------------------------------------------------
def _transport(args: argparse.Namespace) -> Transport:
    if getattr(args, "replay", None):
        return Transport(mode=REPLAY, cassette_dir=args.replay)
    if getattr(args, "record", None):
        return Transport(mode=RECORD, cassette_dir=args.record)
    return Transport(mode=LIVE)


def _clients(args: argparse.Namespace):
    t = _transport(args)
    gh = GitHubClient(repo=args.repo, transport=t)
    devin = DevinClient(transport=t)
    policy = Policy.load(args.policy)
    store = StateStore(gh, branch=args.state_branch)
    t.write_meta({"repo": gh.repo, "org_id": devin.org_id, "command": args.command, "run_id": args.run_id})
    return gh, devin, policy, store, t


def _emit_summary(text: str) -> None:
    path = os.environ.get("GITHUB_STEP_SUMMARY")
    if path:
        with open(path, "a") as fh:
            fh.write(text)
    print(text)


# -- commands -----------------------------------------------------------------
def cmd_doctor(args: argparse.Namespace) -> int:
    """Phase 0: verify every capability the rest of the system assumes."""
    gh, devin, policy, store, _ = _clients(args)
    rows = []

    def check(name: str, fn):
        try:
            detail = fn()
            rows.append((name, "yes", str(detail)[:90]))
        except Exception as exc:
            rows.append((name, "NO", f"{type(exc).__name__}: {exc}"[:90]))

    check("Devin API reachable / identity", lambda: devin.whoami())
    check("Consumption API (budget enforcement)", lambda: devin.daily_consumption())
    check("Playbooks readable", lambda: f"{len(devin.list_sessions(tags=['swarm']))} swarm sessions found")
    check("GitHub repo readable", lambda: gh.repo_info().get("full_name"))
    check("Issues enabled", lambda: gh.repo_info().get("has_issues"))
    check("State branch present", lambda: gh.branch_exists(args.state_branch))
    check("Policy loaded", lambda: f"{len(policy.tiers)} tiers, cap {policy.budget.daily_acu_cap} ACU/day")

    width = max(len(r[0]) for r in rows)
    print(f"swarm {__version__} — capability check\n")
    for name, ok, detail in rows:
        print(f"  [{ok:>3}] {name.ljust(width)}  {detail}")
    return 0 if all(r[1] == "yes" for r in rows[:4]) else 1


def cmd_bootstrap(args: argparse.Namespace) -> int:
    gh, devin, policy, store, _ = _clients(args)
    for label, colour in CLASS_LABEL_COLOURS.items():
        gh.ensure_label(label, colour, "backlog swarm")
    for label in STATE_LABELS:
        gh.ensure_label(label, "ededed", "swarm task state (machine-managed)")
    store.ensure_branch()
    gh.create_orphan_branch("gh-pages", "# Backlog swarm dashboard\n\nGenerated by the reconciler.\n")
    print(f"bootstrapped labels, {args.state_branch} and gh-pages on {gh.repo}")
    return 0


def cmd_scan(args: argparse.Namespace) -> int:
    gh, devin, policy, store, _ = _clients(args)
    findings = run_scanners(args.repo_dir, tools=args.tools.split(","))
    created = file_issues(gh, findings, auto_label=args.auto_label, limit=args.limit, dry_run=args.dry_run)
    lines = [
        "## Swarm scan",
        "",
        f"{len(findings)} distinct package findings from `{args.tools}` · {len(created)} new issues "
        f"(the rest were already tracked — deduplication is on the finding fingerprint, not the title)",
        "",
    ]
    for issue in created:
        num = issue.get("number")
        lines.append(f"- {'#' + str(num) if num else '[dry-run]'} {issue.get('title')}")
    _emit_summary("\n".join(lines) + "\n")
    return 0


def cmd_seed(args: argparse.Namespace) -> int:
    """File the hand-curated tier-2/tier-3 backlog from a YAML definition."""
    import yaml

    gh, devin, policy, store, _ = _clients(args)
    spec = yaml.safe_load(open(args.file).read())
    setup = (spec.get("setup") or "").strip()
    known = existing_fingerprints(gh) if not args.dry_run else {}
    lines = ["## Swarm seed", ""]
    created = 0
    for item in spec.get("issues", []):
        fingerprint = f"curated-{item['id']}"
        if fingerprint in known:
            lines.append(f"- skipped `{item['id']}` — already filed as #{known[fingerprint]}")
            continue
        problem = item["problem"].strip()
        if setup:
            problem += f"\n\n<details><summary>Environment</summary>\n\n{setup}\n\n</details>"
        body = render_issue_body(
            problem=problem,
            affected_paths=item.get("affected_paths") or item["touch_scope"],
            acceptance=item["acceptance"],
            verify=item["verify"],
            issue_class=item["class"],
            touch_scope=item["touch_scope"],
            fingerprint=fingerprint,
            tier=f"tier-{item['tier']}",
            provenance=f"Hand-curated tier-{item['tier']} backlog item (`{item['id']}`).",
        )
        labels = [f"class:{item['class']}", f"tier:{item['tier']}", "swarm:queued"]
        if args.auto_label:
            labels.append("devin:auto")
        if args.dry_run:
            lines.append(f"- [dry-run] {item['title']}  `{labels}`")
            continue
        for label in labels:
            gh.ensure_label(label, CLASS_LABEL_COLOURS.get(label, "ededed"), "backlog swarm")
        issue = gh.create_issue(item["title"], body, labels)
        created += 1
        lines.append(f"- #{issue['number']} {item['title']}")
    lines.insert(2, f"{created} issues filed from `{args.file}` (deduplicated on the curated id).")
    _emit_summary("\n".join(lines) + "\n")
    return 0


def cmd_verify(args: argparse.Namespace) -> int:
    """Run the linked issue's own verification commands as the PR's CI.

    Deliberately GitHub-only: verification runs on every PR in the target repo,
    including ones a human wrote, and should not require a Devin credential.
    """
    gh = GitHubClient(repo=args.repo, transport=_transport(args))
    ok, steps, spec = verify_pr(gh, args.pr, repo_dir=args.repo_dir)
    _emit_summary(verify_summary(args.pr, ok, steps, spec))
    if args.post_status:
        # A commit status, not just a job result: the reconciler reads CI from
        # the statuses API, and a run triggered manually would otherwise leave
        # no trace the merge policy can see.
        sha = gh.get_pr(args.pr)["head"]["sha"]
        gh.set_status(
            sha,
            "success" if ok else "failure",
            "swarm verify",
            f"{sum(s.ok for s in steps)}/{len(steps)} checks from the linked issue",
            target_url=args.status_url or None,
        )
    return 0 if ok else 1


def cmd_dispatch(args: argparse.Namespace) -> int:
    gh, devin, policy, store, _ = _clients(args)
    ledger = store.load()
    ledger.repo = gh.repo
    notes: list[str] = []
    for number in args.issue:
        task, note = dispatch_issue(
            gh, devin, ledger, policy, number, run_id=args.run_id, base_branch=args.base, dry_run=args.dry_run
        )
        notes.append(f"#{number}: {note}")
    if not args.dry_run:
        store.save(ledger, f"chore(swarm): dispatch {', '.join('#' + str(n) for n in args.issue)}")
    _emit_summary(step_summary(ledger, notes, title="Swarm dispatch"))
    return 0


def cmd_nightly(args: argparse.Namespace) -> int:
    """Fan out across the labelled backlog under concurrency and ACU caps."""
    gh, devin, policy, store, _ = _clients(args)
    ledger = store.load()
    ledger.repo = gh.repo

    for issue in gh.list_issues(labels=["devin:auto"]):
        spec = IssueSpec.from_issue(issue)
        task = ledger.get(spec.number) or Task(issue_number=spec.number, state=QUEUED)
        task.issue_title, task.issue_class, task.touch_scope = spec.title, spec.issue_class, spec.touch_scope
        ledger.upsert(task)

    spent = acus_today(devin)
    in_flight = ledger.in_flight()
    unmerged = [t for t in ledger.active() if t not in in_flight]
    to_dispatch, skipped = plan(ledger.queued(), in_flight, policy, spent, holding_scope=unmerged)
    notes = [f"ACUs spent today: {spent:.1f} / cap {policy.budget.daily_acu_cap}"]
    for task in to_dispatch:
        _, note = dispatch_issue(
            gh, devin, ledger, policy, task.issue_number, run_id=args.run_id, base_branch=args.base, dry_run=args.dry_run
        )
        notes.append(f"#{task.issue_number} ({task.issue_class}): {note}")
    for task, reason in skipped:
        notes.append(f"#{task.issue_number}: skipped — {reason}")
    if not args.dry_run:
        store.save(ledger, f"chore(swarm): nightly fan-out ({len(to_dispatch)} dispatched)")
    _emit_summary(step_summary(ledger, notes, title="Swarm nightly fan-out"))
    return 0


def cmd_reconcile(args: argparse.Namespace) -> int:
    gh, devin, policy, store, _ = _clients(args)
    ledger = store.load()
    ledger.repo = gh.repo
    log = reconcile(gh, devin, ledger, policy, dry_run=args.dry_run)
    if not args.dry_run:
        store.save(ledger, f"chore(swarm): reconcile ({len(log)} transitions)")
        if args.publish:
            _publish_dashboard(gh, ledger, args)
    _emit_summary(step_summary(ledger, log))
    return 0


def cmd_dashboard(args: argparse.Namespace) -> int:
    gh, devin, policy, store, _ = _clients(args)
    ledger = store.load()
    html = render(ledger, gh.repo, {"run_id": args.run_id})
    if args.out:
        os.makedirs(args.out, exist_ok=True)
        open(os.path.join(args.out, "index.html"), "w").write(html)
        open(os.path.join(args.out, "metrics.json"), "w").write(render_metrics_json(ledger))
        open(os.path.join(args.out, "state.json"), "w").write(json.dumps(ledger.to_dict(), indent=2) + "\n")
        print(f"wrote dashboard to {args.out}")
    if args.publish:
        _publish_dashboard(gh, ledger, args)
    return 0


def _publish_dashboard(gh: GitHubClient, ledger: Ledger, args: argparse.Namespace) -> None:
    gh.create_orphan_branch("gh-pages", "# Backlog swarm dashboard\n")
    for path, content in (
        ("index.html", render(ledger, gh.repo, {"run_id": args.run_id})),
        ("metrics.json", render_metrics_json(ledger)),
        ("state.json", json.dumps(ledger.to_dict(), indent=2) + "\n"),
    ):
        existing = gh.get_file(path, "gh-pages")
        gh.put_file(path, "gh-pages", content, "chore(swarm): publish dashboard", sha=existing["sha"] if existing else None)
    owner, name = gh.repo.split("/", 1)
    print(f"dashboard published: https://{owner}.github.io/{name}/")


def cmd_state(args: argparse.Namespace) -> int:
    gh, devin, policy, store, _ = _clients(args)
    if args.action == "show":
        print(json.dumps(store.load().to_dict(), indent=2))
    elif args.action == "metrics":
        print(json.dumps(compute(store.load()), indent=2))
    elif args.action == "unpark":
        # A task parked for a reason that no longer holds (a policy defect, a
        # since-corrected issue) needs an explicit operator decision to be
        # re-observed; the reconciler will not un-park anything on its own.
        ledger = store.load()
        task = ledger.get(args.issue or 0)
        if task is None or task.state != NEEDS_HUMAN:
            print(f"#{args.issue}: not a parked task ({task.state if task else 'unknown'})")
            return 1
        target = REVIEW_PENDING if task.pr_url else QUEUED
        task.transition(target, f"unparked by an operator: {args.reason or 'no reason given'}")
        store.save(ledger, f"chore(swarm): unpark #{args.issue}")
        print(f"#{args.issue}: {NEEDS_HUMAN} -> {target}")
    elif args.action == "rebuild":
        owner, name = gh.repo.split("/", 1)
        ledger = rebuild(gh, devin, repo_tag=f"repo:{owner}-{name}")
        print(json.dumps(ledger.to_dict(), indent=2))
        if args.write:
            store.ensure_branch()
            store.save(ledger, "chore(swarm): rebuild ledger from Devin session tags")
            print(f"\nrebuilt {len(ledger.tasks)} tasks from session tags and wrote {args.state_branch}")
    return 0


def cmd_digest(args: argparse.Namespace) -> int:
    """Post the morning digest issue after a nightly run."""
    gh, devin, policy, store, _ = _clients(args)
    ledger = store.load()
    m = compute(ledger)
    c = m["counts"]
    owner, name = gh.repo.split("/", 1)
    body = [
        f"Nightly swarm run `{args.run_id or 'local'}` finished.",
        "",
        f"- **{c['prs_opened']}** pull requests open, **{c['merged']}** merged, "
        f"**{c['needs_human']}** waiting on a human, **{c['failed']}** failed",
        f"- **{m['acus_total']}** ACUs spent · **{m['acus_per_merged_pr'] or '—'}** per merged PR",
        f"- Autonomy rate **{(m['autonomy_rate'] or 0) * 100:.0f}%** · merge rate "
        f"**{(m['merge_rate'] or 0) * 100:.0f}%**",
        f"- Dashboard: https://{owner}.github.io/{name}/",
        "",
        "| Issue | Class | State | PR | ACUs |",
        "|---|---|---|---|---|",
    ]
    for t in sorted(ledger.tasks.values(), key=lambda t: t.issue_number):
        pr = f"{t.pr_url}" if t.pr_url else "—"
        body.append(f"| #{t.issue_number} | `{t.issue_class}` | `{t.state}` | {pr} | {t.acus_consumed:.1f} |")
    if m["failures"]:
        body += ["", "**Failures by category:** " + ", ".join(f"`{k}` ×{v}" for k, v in m["failures"].items())]
    text = "\n".join(body)
    if args.dry_run:
        print(text)
    else:
        issue = gh.create_issue(f"Swarm digest — {args.run_id or 'nightly'}", text, ["swarm:digest"])
        print(f"digest posted: {issue.get('html_url')}")
    return 0


def cmd_replay(args: argparse.Namespace) -> int:
    """Walk a recorded run end to end with no credentials. Nothing is invented."""
    # `--replay <dir>` (the global flag every other command takes) and
    # `--fixtures <dir>` both name the same recording.
    fixtures = args.replay or args.fixtures
    meta = read_meta(fixtures)
    t = Transport(mode=REPLAY, cassette_dir=fixtures)
    # The recorded URLs embed the repo and org the run used, so replay has to
    # address the same ones; the credentials are placeholders and never sent.
    gh = GitHubClient(repo=meta.get("repo", args.repo or "owner/repo"), token="replay", transport=t)
    devin = DevinClient(api_key="replay", org_id=meta.get("org_id", "replay"), transport=t)
    policy = Policy.load(args.policy)
    store = StateStore(gh, branch=args.state_branch)

    banner = "═" * 78
    print(f"{banner}\n  REPLAY MODE — recorded responses from a real run in {fixtures}\n"
          f"  No network calls are made. No data is synthesised.\n{banner}\n")
    ledger = store.load()
    for tick in range(1, args.ticks + 1):
        log = reconcile(gh, devin, ledger, policy, dry_run=True)
        print(f"── tick {tick} " + "─" * 60)
        for line in log or ["(no transitions)"]:
            print(f"   {line}")
    print("\n" + step_summary(ledger, [], title="Replay result"))
    if args.out:
        os.makedirs(args.out, exist_ok=True)
        open(os.path.join(args.out, "index.html"), "w").write(render(ledger, gh.repo, {"run_id": "replay"}))
        print(f"dashboard written to {args.out}/index.html (rendered from recorded data)")
    return 0


# -- parser -------------------------------------------------------------------
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="swarm", description="Autonomous backlog swarm for Devin")
    p.add_argument("--version", action="version", version=__version__)
    p.add_argument("--repo", default=os.environ.get("SWARM_REPO", ""), help="owner/name of the target repo")
    p.add_argument("--policy", default=os.environ.get("SWARM_POLICY"))
    p.add_argument("--state-branch", default=STATE_BRANCH)
    p.add_argument("--run-id", default=os.environ.get("GITHUB_RUN_ID"))
    p.add_argument("--record", help="record all HTTP traffic into this fixture directory")
    p.add_argument("--replay", help="serve all HTTP traffic from this fixture directory")
    sub = p.add_subparsers(dest="command", required=True)

    d = sub.add_parser("doctor", help="verify API capabilities and permissions")
    d.set_defaults(func=cmd_doctor)

    b = sub.add_parser("bootstrap", help="create labels, state branch and gh-pages")
    b.set_defaults(func=cmd_bootstrap)

    s = sub.add_parser("scan", help="run OSS scanners and file deduplicated issues")
    s.add_argument("--repo-dir", default=".", help="checkout of the target repo to scan")
    s.add_argument("--tools", default="osv-scanner,pip-audit")
    s.add_argument("--limit", type=int, default=25)
    s.add_argument("--auto-label", action="store_true", help="also apply devin:auto (dispatches immediately)")
    s.add_argument("--dry-run", action="store_true")
    s.set_defaults(func=cmd_scan)

    sd = sub.add_parser("seed", help="file the hand-curated tier-2/tier-3 backlog from YAML")
    sd.add_argument("--file", default="backlog/superset.yaml")
    sd.add_argument("--auto-label", action="store_true")
    sd.add_argument("--dry-run", action="store_true")
    sd.set_defaults(func=cmd_seed)

    vf = sub.add_parser("verify", help="run a PR's linked issue verification commands (the fork's CI)")
    vf.add_argument("--pr", type=int, required=True)
    vf.add_argument("--repo-dir", default=".")
    vf.add_argument("--post-status", action="store_true", help="publish a `swarm verify` commit status")
    vf.add_argument("--status-url", default=os.environ.get("SWARM_STATUS_URL", ""))
    vf.set_defaults(func=cmd_verify)

    di = sub.add_parser("dispatch", help="create a Devin session for one or more issues")
    di.add_argument("--issue", type=int, action="append", required=True)
    di.add_argument("--base", default="master")
    di.add_argument("--dry-run", action="store_true")
    di.set_defaults(func=cmd_dispatch)

    n = sub.add_parser("nightly", help="conflict-aware fan-out across the labelled backlog")
    n.add_argument("--base", default="master")
    n.add_argument("--dry-run", action="store_true")
    n.set_defaults(func=cmd_nightly)

    r = sub.add_parser("reconcile", help="advance every non-terminal task by one tick")
    r.add_argument("--dry-run", action="store_true")
    r.add_argument("--publish", action="store_true", help="also publish the dashboard to gh-pages")
    r.set_defaults(func=cmd_reconcile)

    da = sub.add_parser("dashboard", help="render the static dashboard")
    da.add_argument("--out", default="site")
    da.add_argument("--publish", action="store_true")
    da.set_defaults(func=cmd_dashboard)

    st = sub.add_parser("state", help="inspect or rebuild the ledger")
    st.add_argument("action", choices=["show", "metrics", "rebuild", "unpark"])
    st.add_argument("--issue", type=int, help="issue number to unpark")
    st.add_argument("--reason", default="", help="why the parked task is being re-observed")
    st.add_argument("--write", action="store_true", help="write the rebuilt ledger back to the state branch")
    st.set_defaults(func=cmd_state)

    dg = sub.add_parser("digest", help="post the morning digest issue")
    dg.add_argument("--dry-run", action="store_true")
    dg.set_defaults(func=cmd_digest)

    rp = sub.add_parser("replay", help="replay a recorded run offline, with no credentials")
    rp.add_argument("--fixtures", default="fixtures/latest", help="the recorded run to walk (same as --replay)")
    # accepted after the subcommand too, so `swarm replay --replay fixtures/run-…` works
    rp.add_argument("--replay", default=None, help=argparse.SUPPRESS)
    rp.add_argument("--ticks", type=int, default=6)
    rp.add_argument("--out", default="")
    rp.set_defaults(func=cmd_replay)
    return p


def main(argv: list[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    return int(args.func(args) or 0)


if __name__ == "__main__":
    sys.exit(main())
